In [1]:
import pandas as pd 
import numpy as np

users = pd.read_csv('./data/users.dat')
movies = pd.read_csv('./data/movies.dat')
ratings = pd.read_csv('./data/ratings.dat')

In [2]:
def RMSE(y_true, y_pred):
    return np.sqrt(np.mean((np.array(y_true) - np.array(y_pred)) ** 2))

def score(model):
    id_pairs = zip(X_test['user_id'], X_test['movie_id'])
    y_pred = np.array([model(user, movie) for (user, movie) in id_pairs])
    y_true = np.array(X_test['rating'])
    return RMSE(y_true, y_pred)

In [3]:
# train, test set 분리
from sklearn.model_selection import train_test_split
X = ratings.copy()
y = ratings['user_id']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, stratify=y)

In [4]:
rating_matrix = X_train.pivot(index='user_id', columns='movie_id', values='rating')

In [5]:
rating_matrix.head(3)

movie_id,1,2,3,4,5,6,7,8,9,10,...,1672,1673,1674,1675,1676,1677,1679,1680,1681,1682
user_id,,,,,,,,,,,,,,,,,,,,,
1,NaN,3.0,4.0,3.0,NaN,NaN,4.0,1.0,5.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 1. CF - Basic

In [6]:
from sklearn.metrics.pairwise import cosine_similarity
matrix_dummy = rating_matrix.copy().fillna(0)

def CF_simple(user_id, movie_id):
    if movie_id in rating_matrix:
        sim_scores = user_similarity[user_id].copy()
        movie_ratings = rating_matrix[movie_id].copy()
        none_rating_idx = movie_ratings[movie_ratings.isnull()].index # movie_id에 대한 rating이 없는 user_id 인덱스
        movie_ratings = movie_ratings.dropna()
        sim_scores = sim_scores.drop(none_rating_idx) # movie_id를 본 user_id의 rating만 고려
        mean_rating = np.dot(sim_scores, movie_ratings) / sim_scores.sum() # 유사도점수에 따라 가중 평균
    else:
        mean_rating = 3.0
    
    return mean_rating

### 1-1. Cosine Similarity

In [7]:
user_similarity = cosine_similarity(matrix_dummy, matrix_dummy)
user_similarity = pd.DataFrame(user_similarity, index=rating_matrix.index, columns=rating_matrix.index)

In [8]:
score(CF_simple)

1.0144316669472162

### 1-2. Pearson Correlation Coefficient

In [16]:
user_similarity = matrix_dummy.T.corr(method="pearson")

In [18]:
user_similarity

user_id,1,2,3,4,5,6,7,8,9,10,...,934,935,936,937,938,939,940,941,942,943
user_id,,,,,,,,,,,,,,,,,,,,,
1,1.000000,0.074367,-0.006028,0.034859,0.192396,0.207876,0.192667,0.227489,0.008460,0.182204,...,0.199129,0.065911,0.158488,0.103771,0.108851,0.076527,0.207330,0.112171,0.091264,0.232930
2,0.074367,1.000000,0.086285,0.198324,-0.004568,0.166105,0.035687,0.033144,0.155299,0.041892,...,0.093863,0.243800,0.260024,0.344691,0.210037,0.219712,0.183259,0.171769,0.048686,0.025006
3,-0.006028,0.086285,1.000000,0.188477,-0.008539,0.017726,0.008912,0.056490,0.009164,-0.012169,...,0.005004,0.039802,0.083191,0.043398,0.074022,0.015899,0.126065,0.038320,0.030749,-0.002068
4,0.034859,0.198324,0.188477,1.000000,-0.027163,0.038207,0.046847,0.065988,0.120893,0.035606,...,0.011308,0.034846,0.094933,0.165950,0.045315,0.025715,0.164395,0.131990,0.129134,0.003657
5,0.192396,-0.004568,-0.008539,-0.027163,1.000000,0.064443,0.193414,0.175568,0.012209,0.086562,...,0.169738,0.061172,0.005888,0.004757,0.069500,0.051846,0.153061,0.056293,0.014874,0.181491
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,0.076527,0.219712,0.015899,0.025715,0.051846,0.042062,0.016873,0.109328,-0.014695,-0.011679,...,0.050200,0.378691,0.146515,0.159594,0.324678,1.000000,0.065071,0.142163,-0.010433,0.048948
940,0.207330,0.183259,0.126065,0.164395,0.153061,0.208977,0.149417,0.108642,0.121965,0.162459,...,0.144852,0.097814,0.110687,0.129825,0.087797,0.065071,1.000000,0.109227,0.132393,0.093384
941,0.112171,0.171769,0.038320,0.131990,0.056293,0.100899,-0.016316,0.091620,0.182873,0.064755,...,-0.003920,0.141464,0.284623,0.046754,0.243257,0.142163,0.109227,1.000000,0.018671,0.057651
942,0.091264,0.048686,0.030749,0.129134,0.014874,0.199871,0.170241,0.088709,0.056386,0.174053,...,0.130603,0.023638,0.015052,0.041370,0.027808,-0.010433,0.132393,0.018671,1.000000,0.106404
943,0.232930,0.025006,-0.002068,0.003657,0.181491,0.113278,0.179248,0.161072,0.045998,0.048061,...,0.113872,0.103862,0.052920,0.008142,0.093025,0.048948,0.093384,0.057651,0.106404,1.000000

In [ ]:
score(CF_simple)

## 2. CF - Neighborhood based